name = "meinTest"
uuid = "bfc0465b-491e-4267-bc55-e149fadc8df3"
authors = ["Aaron Peikert", "Maximilian S. Ernst", "Nicklas Hafiz"]
version = "0.1.0"

[deps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Optim = "1"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
